### ISSUE TITLE
the removed animation played when page state changed (document visibilitychange event)

### ISSUE THREAD

**Issue by elvira1112** [juliangarnier/anime#560]
Describe the bug: 
  I remove an animation, but it played when i trigger the document visibilitychange event. 
  I found that It doesn't remove the animation when i removed. And when it run into visibilitychange event, it played all of pause animation. 

To Reproduce:
1. remove an animation
2. i slide my desktop on my mac, i guess switch tab also can trigger the bug. Anyway, to trigger the visibilitychange event.

Expected behavior:
1. my removed animation can not replay

Desktop:
browser chrome v73.0.3683.75

**Comment by juliangarnier** [comment]
Fixed in v3.1.0!

**Comment by fljot** [comment]
@juliangarnier @chrisbrown-io I think bug is still there, at least partially perhaps.

Steps to reproduce:
1) deactivate tab (so it would become `document.visibilityState === 'hidden'`)
2) run `anime.reset()` (while `document.visibilityState === 'hidden'`)
3) get back to tab, so it would trigger visibilitychange event

Actual results:
Anime restores animations https://github.com/juliangarnier/anime/blob/3.2.0/src/index.js#L875 including those which were explicitly paused by user (in step 2)
![image](https://user-images.githubusercontent.com/404216/86017770-1d887c00-ba2d-11ea-8831-72837347ecc6.png)
